import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { emitCSharp } from './emit.js';
import { parseSchema } from './parse.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const SCHEMA_PATH = resolve(__dirname, '../../../schema.ts');
const OUTPUT_PATH = resolve(__dirname, '../../../apps/api/Atlas.Api/Generated/Schema.g.cs');
const SUPPORT_OUTPUT = resolve(
  __dirname,
  '../../../apps/api/Atlas.Api/Generated/SchemaSupport.g.cs',
);

function generate(): { schema: string; support: string } {
  const parsed = parseSchema(SCHEMA_PATH);
  const schema = emitCSharp(parsed.models);
  const support = supportFile();
  return { schema, support };
}

function supportFile(): string {
  return `// <auto-generated>
// Generated by @atlas/schema-codegen. DO NOT EDIT.
// </auto-generated>
#nullable enable

using System;
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Atlas.Schema;

public interface IBrandedId
{
    string Value { get; }
    static abstract string Prefix { get; }
}

public sealed class BrandedIdJsonConverter<TId> : JsonConverter<TId>
    where TId : struct, IBrandedId
{
    public override TId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var raw = reader.GetString() ?? throw new JsonException("expected string branded id, got null");
        if (!raw.StartsWith(TId.Prefix))
            throw new JsonException($"expected '{TId.Prefix}' prefix, got '{raw}'");
        return (TId)Activator.CreateInstance(typeof(TId), raw)!;
    }

    public override void Write(Utf8JsonWriter writer, TId value, JsonSerializerOptions options)
        => writer.WriteStringValue(value.Value);
}

public sealed class JsonStringEnumMemberConverter<TEnum> : JsonConverter<TEnum>
    where TEnum : struct, Enum
{
    public override TEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var raw = reader.GetString() ?? throw new JsonException("expected string enum, got null");
        foreach (var field in typeof(TEnum).GetFields())
        {
            var attr = (EnumMemberAttribute?)Attribute.GetCustomAttribute(field, typeof(EnumMemberAttribute));
            if (attr?.Value == raw && field.GetValue(null) is TEnum value) return value;
        }
        if (Enum.TryParse<TEnum>(raw, ignoreCase: true, out var direct)) return direct;
        throw new JsonException($"unknown enum member '{raw}' for {typeof(TEnum).Name}");
    }

    public override void Write(Utf8JsonWriter writer, TEnum value, JsonSerializerOptions options)
    {
        var field = typeof(TEnum).GetField(value.ToString())
            ?? throw new JsonException($"missing field for enum value {value}");
        var attr = (EnumMemberAttribute?)Attribute.GetCustomAttribute(field, typeof(EnumMemberAttribute));
        writer.WriteStringValue(attr?.Value ?? value.ToString());
    }
}
`;
}

function cmd(): string {
  const arg = process.argv[2];
  if (!arg) throw new Error('usage: cli.ts <emit|check>');
  return arg;
}

function main() {
  const action = cmd();
  const { schema, support } = generate();

  if (action === 'emit') {
    mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
    writeFileSync(OUTPUT_PATH, schema, 'utf8');
    writeFileSync(SUPPORT_OUTPUT, support, 'utf8');
    process.stdout.write(`wrote ${OUTPUT_PATH}\nwrote ${SUPPORT_OUTPUT}\n`);
    return;
  }

  if (action === 'check') {
    const drift: string[] = [];
    for (const [path, expected] of [
      [OUTPUT_PATH, schema],
      [SUPPORT_OUTPUT, support],
    ] as const) {
      if (!existsSync(path)) {
        drift.push(`${path} missing`);
        continue;
      }
      const actual = readFileSync(path, 'utf8');
      if (actual !== expected) drift.push(`${path} out of date — run \`pnpm run codegen\``);
    }
    if (drift.length > 0) {
      for (const d of drift) process.stderr.write(d + '\n');
      process.exit(1);
    }
    process.stdout.write('schema generated files are up to date\n');
    return;
  }

  throw new Error(`unknown command: ${action}`);
}

main();
