import type { PropertyModel, SchemaModel } from './parse.js';

const HEADER = `// <auto-generated>
// Generated by @atlas/schema-codegen from schema.ts at the repo root.
// DO NOT EDIT -- run \`pnpm run codegen\` to refresh.
// </auto-generated>
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Atlas.Schema;
`;

export function emitCSharp(models: SchemaModel[]): string {
  const enumLookup = new Set(
    models.filter((m) => m.kind === 'enum' || m.kind === 'brandedId').map((m) => m.name),
  );
  const recordLookup = new Set(models.filter((m) => m.kind === 'record').map((m) => m.name));
  const aliasLookup = new Map<string, string>();
  for (const m of models) {
    if (m.kind === 'alias') aliasLookup.set(m.name, m.tsType);
  }

  const parts: string[] = [HEADER];

  for (const m of models) {
    if (m.kind === 'brandedId') parts.push(emitBrandedId(m.name, m.prefix));
    else if (m.kind === 'enum') parts.push(emitEnum(m.name, m.values));
  }

  for (const m of models) {
    if (m.kind === 'record')
      parts.push(emitRecord(m.name, m.properties, enumLookup, recordLookup, aliasLookup));
  }

  return parts.join('\n');
}

function emitBrandedId(name: string, prefix: string): string {
  return `
[JsonConverter(typeof(BrandedIdJsonConverter<${name}>))]
public readonly record struct ${name}(string Value) : IBrandedId
{
    public static string Prefix => "${prefix}_";
    public override string ToString() => Value;
    public static ${name} Parse(string raw) =>
        raw.StartsWith(Prefix) && raw.Length > Prefix.Length
            ? new ${name}(raw)
            : throw new System.FormatException($"expected id with prefix '${prefix}_', got '{raw}'");
}
`;
}

function emitEnum(name: string, values: string[]): string {
  const members = values
    .map((v) => `    [System.Runtime.Serialization.EnumMember(Value = "${v}")] ${pascal(v)},`)
    .join('\n');
  return `
[JsonConverter(typeof(JsonStringEnumMemberConverter<${name}>))]
public enum ${name}
{
${members}
}
`;
}

function emitRecord(
  name: string,
  properties: PropertyModel[],
  enumLookup: Set<string>,
  recordLookup: Set<string>,
  aliasLookup: Map<string, string>,
): string {
  if (properties.length === 0) {
    return `\npublic sealed record ${name}();\n`;
  }
  const lines = properties.map((p) => {
    const csType = mapTsTypeToCs(p.tsType, enumLookup, recordLookup, aliasLookup);
    const nullableSuffix = p.optional && !csType.endsWith('?') ? '?' : '';
    return `    [property: JsonPropertyName("${p.name}")] ${csType}${nullableSuffix} ${pascal(p.name)}`;
  });
  return `\npublic sealed record ${name}(\n${lines.join(',\n')}\n);\n`;
}

// ─── TS type → C# type mapping ─────────────────────────────────────────────

function mapTsTypeToCs(
  raw: string,
  enumLookup: Set<string>,
  recordLookup: Set<string>,
  aliasLookup: Map<string, string>,
): string {
  const t = raw.trim();

  // Nullable via union with null
  const nullUnion = splitTopLevelUnion(t).filter((p) => p !== 'null' && p !== 'undefined');
  const hadNull = nullUnion.length !== splitTopLevelUnion(t).length;
  const body = nullUnion.length === 1 ? nullUnion[0]!.trim() : t;

  const cs = mapTsTypeCore(body, enumLookup, recordLookup, aliasLookup);
  return hadNull ? appendNullable(cs) : cs;
}

function mapTsTypeCore(
  t: string,
  enumLookup: Set<string>,
  recordLookup: Set<string>,
  aliasLookup: Map<string, string>,
): string {
  // Arrays: T[] or Array<T>
  if (t.endsWith('[]')) {
    const inner = t.slice(0, -2).trim();
    return `IReadOnlyList<${mapTsTypeCore(inner, enumLookup, recordLookup, aliasLookup)}>`;
  }
  if (t.startsWith('Array<') && t.endsWith('>')) {
    const inner = t.slice(6, -1).trim();
    return `IReadOnlyList<${mapTsTypeCore(inner, enumLookup, recordLookup, aliasLookup)}>`;
  }

  // Record<K,V>
  const recordMatch = t.match(/^Record<([^,]+),\s*(.+)>$/);
  if (recordMatch) {
    const k = mapTsTypeCore(recordMatch[1]!.trim(), enumLookup, recordLookup, aliasLookup);
    const v = mapTsTypeCore(recordMatch[2]!.trim(), enumLookup, recordLookup, aliasLookup);
    return `IReadOnlyDictionary<${k}, ${v}>`;
  }

  // Resolve aliases (Iso8601 = string, GitSha = string, etc.) to their target.
  if (aliasLookup.has(t)) {
    return mapTsTypeCore(aliasLookup.get(t)!, enumLookup, recordLookup, aliasLookup);
  }

  // Known enums / branded IDs / records → pass through by name
  if (enumLookup.has(t) || recordLookup.has(t)) return t;

  // Primitives
  switch (t) {
    case 'string':
      return 'string';
    case 'number':
      return 'double';
    case 'boolean':
      return 'bool';
    case 'unknown':
    case 'any':
      return 'System.Text.Json.JsonElement';
  }

  // Template literals like `${string}@${GitSha}` — fall back to string
  if (t.startsWith('`')) return 'string';

  // Union of multiple non-null things: fall back to JsonElement (bump in Phase 3+)
  if (splitTopLevelUnion(t).length > 1) return 'System.Text.Json.JsonElement';

  // Inline object or union — dump as JsonElement; refine per-field later
  if (t.startsWith('{') || t.startsWith('(')) return 'System.Text.Json.JsonElement';

  // Parameterized generic: bail to JsonElement; refine later
  if (/[<>]/.test(t)) return 'System.Text.Json.JsonElement';

  // Unknown bare identifier — assume it's a sibling type
  return t;
}

function splitTopLevelUnion(t: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let buf = '';
  for (const ch of t) {
    if (ch === '<' || ch === '(' || ch === '{' || ch === '[') depth++;
    else if (ch === '>' || ch === ')' || ch === '}' || ch === ']') depth--;
    if (ch === '|' && depth === 0) {
      parts.push(buf.trim());
      buf = '';
    } else {
      buf += ch;
    }
  }
  if (buf.trim()) parts.push(buf.trim());
  return parts;
}

function appendNullable(cs: string): string {
  if (cs.endsWith('?')) return cs;
  return `${cs}?`;
}

function pascal(s: string): string {
  return s
    .split(/[_-]/)
    .map((part) => (part ? part[0]!.toUpperCase() + part.slice(1) : ''))
    .join('');
}
